/**
 * AI Client
 *
 * Abstract interface for AI calls. Has two implementations:
 *   - MockClient: returns canned responses (Phase 3a, no API calls)
 *   - ClaudeClient: real Anthropic API calls (Phase 3b, future)
 *
 * Pipeline stages depend on AiClient (the interface), not a concrete impl.
 * Phase 3a → 3b becomes a 1-line swap in the factory.
 */

export interface AiTextRequest {
  /** Prompt text. */
  prompt: string;
  /** Optional system prompt. */
  system?: string;
  /** Max tokens to generate. */
  maxTokens?: number;
  /** Force JSON output? Most stages set this to true. */
  jsonMode?: boolean;
}

export interface AiVisionRequest {
  /** Prompt text describing what to extract from the image. */
  prompt: string;
  /** Image as raw bytes. */
  imageBytes: Uint8Array;
  /** Image mime type (image/png, image/webp, image/jpeg). */
  mimeType: string;
  /** Optional system prompt. */
  system?: string;
  jsonMode?: boolean;
}

export interface AiClient {
  /** Send text-only request, return raw response text. */
  generateText(req: AiTextRequest): Promise<string>;
  /** Send request with image attachment, return raw response text. */
  generateVision(req: AiVisionRequest): Promise<string>;
}

/**
 * Factory: choose the right client based on options.
 */
export function createAiClient(opts: { mock: boolean; apiKey?: string }): AiClient {
  if (opts.mock) {
    return new MockClient();
  }
  // Phase 3b will replace this with ClaudeClient
  throw new Error(
    "Live AI mode not yet implemented. Use --mock for now (Phase 3a)."
  );
}

/**
 * MockClient
 *
 * Returns canned JSON responses for testing the pipeline end-to-end
 * without spending API credits. Each pipeline stage knows how to
 * recognise its own mock response.
 */
class MockClient implements AiClient {
  async generateText(req: AiTextRequest): Promise<string> {
    // Very simple mock: pipeline stages will pre-stuff their canned data
    // via the prompt's marker tag. See pipeline/*.ts for usage.
    const marker = extractMarker(req.prompt);
    return MOCK_RESPONSES[marker] ?? "{}";
  }

  async generateVision(req: AiVisionRequest): Promise<string> {
    const marker = extractMarker(req.prompt);
    return MOCK_RESPONSES[marker] ?? "{}";
  }
}

/** Extract the [MOCK:xxx] marker from a prompt, used to look up canned data. */
function extractMarker(prompt: string): string {
  const match = prompt.match(/\[MOCK:([a-z_-]+)\]/);
  return match?.[1] ?? "default";
}

/**
 * Canned responses keyed by marker. Pipeline stages use markers like
 * [MOCK:outline] in their prompts; the mock client returns the matching
 * JSON. This keeps mock data co-located with this client for easy tweaking.
 */
const MOCK_RESPONSES: Record<string, string> = {
  outline: JSON.stringify({
    title: "Mock Adventure",
    slug: "mock-adventure",
    synopsis: "A test adventure generated by the mock pipeline.",
    tone: "heroic fantasy",
    chapters: [
      {
        id: "chapter-1",
        title: "The Beginning",
        synopsis: "The party arrives.",
        startPage: 1,
        endPage: 3,
      },
    ],
  }),

  content: JSON.stringify({
    rooms: [
      {
        id: "room-1",
        code: "A1",
        name: "Entry Hall",
        readAloud: "<p>You enter a dim hall lit by a single torch.</p>",
        gmNotes: "<p>The torch is magical and never extinguishes.</p>",
        connections: [],
        skillChecks: [],
      },
    ],
    npcs: [
      {
        id: "guard-captain",
        name: "Guard Captain",
        isUnique: false,
        compendiumSlug: "guard-captain",
      },
    ],
    items: [
      {
        id: "longsword-plus-1",
        name: "+1 Longsword",
        quantity: 1,
        compendiumSlug: "longsword",
        location: "treasure",
        locationId: "room-1",
      },
    ],
    encounters: [],
    hazards: [],
    handouts: [],
  }),

  map_walls: JSON.stringify({
    walls: [
      { c: [0.0, 0.0, 1.0, 0.0], light: 20, move: 20, sight: 20, door: 0, ds: 0 },
      { c: [1.0, 0.0, 1.0, 1.0], light: 20, move: 20, sight: 20, door: 0, ds: 0 },
      { c: [1.0, 1.0, 0.0, 1.0], light: 20, move: 20, sight: 20, door: 0, ds: 0 },
      { c: [0.0, 1.0, 0.0, 0.0], light: 20, move: 20, sight: 20, door: 0, ds: 0 },
    ],
    lights: [],
    sounds: [],
  }),

  image_classify: JSON.stringify({
    type: "battle_map",
    confidence: 0.9,
  }),
};
